spring.application.name: api-gateway

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: resource-server
            uri: ${NSA2_RESOURCE_SERVER_URI:http://127.0.0.1:8082}
            predicates:
              - Path=/resource-server/**
            filters:
              - StripPrefix=1
              - AddRequestHeader=Origin, http://nsa2-gateway:8080
              - TokenRelay=

spring.threads.virtual.enabled: true

spring.security.oauth2.client:
  registration:
    nsa2:
      provider: spring
      client-id: nsa2
      client-secret: secret
      authorization-grant-type: authorization_code
      scope: openid,profile,nsa2.user.all,nsa2.user.read,nsa2.user.write,nsa2.admin
      redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"

  provider:
    spring:
      issuer-uri: http://localhost:8081